name: Publish Blogs
description: When pushing Zenn articles to GitHub, convert them to Qiita format and publish them.
author: Naoki Chihara

inputs:
  root:
    required: false
    default: "./qiita"
    description: "Root directory path"
  qiita-token:
    required: true
    description: 'Qiita API token'
  convert-commit-message:
    required: false
    default: "Convert Zenn articles to Qiita format"
    description: "Commit message for converting Zenn articles to Qiita format"
  qiitacli-commit-message:
    required: false
    default: "Updated by qiita-cli"
    description: "Qiita commit message"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '21'

    - name: Install dependencies
      run: |
        npm install @types/yargs git-url-parse yargs zenn-cli
        npm install --save-dev @qiita/qiita-cli @types/git-url-parse @types/js-yaml @types/node ts-node typescript
      shell: bash

    - name: Get changed markdown files
      id: files
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^articles/.*\.md$" > $GITHUB_WORKSPACE/changed_files.txt
        echo "Changed markdown files:"
        cat $GITHUB_WORKSPACE/changed_files.txt
      continue-on-error: true
      shell: bash

    - name: Convert Zenn articles to Qiita format
      run: |
        for file in $(cat $GITHUB_WORKSPACE/changed_files.txt); do
          filename=$(basename "$file" .md)
          echo "🚀 Convert $file to Qiita format"
          if [[ "$file" != articles/* ]]; then
            echo "⚠️ invalid file path: $file"
            if [[ -f "qiita/public/$filename.md" ]]; then
              echo "delete qiita/public/$filename.md cuz it's not included in articles/"
              rm "qiita/public/$filename.md"
            fi
            continue
          fi

          if [[ ! -f "qiita/public/$filename.md" ]] && grep -q "published: true" "$file"; then
            cd ./qiita
            npx qiita new "$filename"
            cd ../
          fi

          echo "🚚 Convert $file to qiita/public/$filename.md"
          ./node_modules/.bin/ts-node --project ${{ github.action_path }}/tsconfig.json ${{ github.action_path }}/scripts/ztoq.tsx "$file" "./qiita/public/$filename.md"
        done
      shell: bash
      if: steps.files.outcome == 'success'

    - name: Commit converted Qiita articles
      run: |
        rm $GITHUB_WORKSPACE/changed_files.txt
        git config --local user.name ${{ github.actor }}
        git config --local user.email ${{ github.actor }}@users.noreply.github.com
        git add qiita/public/*.md
        git commit -m "${{ inputs.convert-commit-message }}"
        git push
      shell: bash
      if: steps.files.outcome == 'success'

    - name: Publish Qiita articles
      uses: increments/qiita-cli/actions/publish@v1
      with:
        qiita-token: ${{ inputs.qiita-token }}
        root: ${{ inputs.root }}
        commit-message: ${{ inputs.qiitacli-commit-message }}
